name: CD deploy
"on":
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  build_an_image_and_push_it:
    name: "Build an image and push it to the Docker Hub"
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Approve deploy
        uses: powerdot/telegram-manual-approval@main
        with:
          TELEGRAM_KEY: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-docker-action@v4
      - name: Login to the Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ananotherartem/licenser:latest
      - name: Setup Golang
        uses: actions/setup-go@v5.5.0
      - name: Compile binaries for all popular platforms
        run: sudo bash ./.github/workflows/compile_commands.sh
      - name: Release version
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: true
          title: The latest version of the Licenser program (This Github release was created by automatic Github Actions workflow)
          files: |
            licenser*
