name: CD deploy
"on":
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  build_an_image_and_push_it:
    name: "Build an image and push it to the Docker Hub"
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
      - name: Review PR
        uses: sturdy-dev/codeball-action@v2
        with:
          approvePullRequests: "true"
          labelPullRequestsWhenApproved: "true"
          labelPullRequestsWhenReviewNeeded: "false"
          failJobsWhenReviewNeeded: "true"
      - name: Setup Docker
        uses: docker/setup-docker-action@v4
      - name: Cache Docker layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          continue-on-error: true
      - name: Login to the Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ananotherartem/licenser:latest
