name: CD deploy
"on":
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  build_an_image_and_push_it:
    name: "Build an image and push it to the Docker Hub"
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    strategy:
      fail-fast: true
      matrix:
        compile_commands:
          - env GOOS=linux GOARCH=amd64; go build -o licenser_linux_amd64
          - env GOOS=linux GOARCH=arm64; go build -o licenser_linux_arm64
          - env GOOS=darwin GOARCH=amd64; go build -o licenser_macos_amd64
          - env GOOS=darwin GOARCH=arm64; go build -o licenser_macos_arm64
          - env GOOS=windows GOARCH=amd64; go build -o licenser_windows_amd64.exe
    steps:
      - name: Approve deploy
        uses: powerdot/telegram-manual-approval@main
        with:
          TELEGRAM_KEY: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-docker-action@v4
      - name: Login to the Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ananotherartem/licenser:latest
      - name: Setup Golang
        uses: actions/setup-go@v5.5.0
      - name: Compile binaries for all popular platforms
        run: exec ${{ matrix.compile_commands }}
